config/routes.rb
Rails.application.routes.draw do
  root 'statics#home'
  get    '/signup',       to: 'users#new'
  get    '/login',        to: 'sessions#new'
  get    '/bookings',     to: 'statics#bookings'
  get    '/contact',      to: 'statics#contact'
  post   '/login',        to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :bookings,            only: [:create, :destroy, :new]
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def home
    redirect_to current_user if logged_in?
  end
  
  def bookings
  end
  
  def contact
  end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/statics/bookings.html.erb
<% provide(:title, "Bookings") %>
<div class="center">
  <h1>Bookings</h1>
  <h2>There are currently no bookings.</h2>
  <%= link_to "Make a booking", new_booking_path, class: "btn btn-lg btn-primary" %>

</div>

app/views/statics/contact.html.erb
<% provide(:title, "Contact") %>
<div class="center">
  <h1>Contact</h1>
  Squash Coach: Brendon Woodhead, brendon@wabbit.co.nz<br>
  Director of Squash: Helen Chileshe, h.chileshe@stpauls.school.nz<br>
  Site Developer: Nathan Cleaver, n.cleaver@stpauls.school.nz
</div>

app/views/statics/home.html.erb
<% provide(:title, 'Squash') %>
<div class="center jumbotron">
  <h1>Squash Booking System</h1>

  <h2>
    This is the home page for the
    St Paul's Collegiate School
    squash court booking system.
  </h2>

  <%= link_to "Sign up now!", 'signup', class: "btn btn-lg btn-primary" %>
</div>