config/routes.rb
Rails.application.routes.draw do
  root 'statics#home'
  get    '/signup',       to: 'users#new'
  get    '/login',        to: 'sessions#new'
  get    '/bookings',     to: 'statics#bookings'
  get    '/contact',      to: 'statics#contact'
  post   '/login',        to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :bookings,            only: [:create, :destroy, :new]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse noradius">
  <div class="container">
    <%= link_to "iLearn", 'https://ilearn.stpauls.school.nz', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Bookings", bookings_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) && !user.admin?%>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= favicon_link_tag %>
  </head>
  <body>
    <% if logged_in? %>
      <a href=<%=root_path%>><img src="/assets/logo_hori.png"
               alt="St Paul's Logo" id="schoollogo"></a>
    <% else %>
      <a href=<%=current_user%>><img src="/assets/logo_hori.png"
               alt="St Paul's Logo" id="schoollogo"></a>
    <% end %>
    <%= render 'layouts/header' %>
    
    <div class="container">
      <% flash.each do |message_type, message| %>
         <div class="alert alert-<%= message_type %>"><%= message %></div>
       <% end %>
       <%= yield %>
     </div>
    
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>